pre-commit autoupdate
CoefficientSystems/coefficient-cookiecutter pull request #60
Opened 2022-06-24 11:10 UTC by hicksl

Run pre-commit autoupdate on outer repo, copy updates to inner. Perform manual checks.

2022-06-24 11:11 UTC, hicksl commented
Passing manual checks.

2022-06-24 11:36 UTC, hicksl commented
Closes #56

2022-06-25 11:24 UTC, john-sandall requested changes

2022-06-25 11:24 UTC, john-sandall commented on .pre-commit-config.yaml
>  exclude: "{{cookiecutter.repo_name}}"
We can bump precommit version also to 2.19.0
https://github.com/pre-commit/pre-commit/releases

2022-06-25 11:24 UTC, john-sandall commented on .pre-commit-config.yaml
>  exclude: "{{cookiecutter.repo_name}}"
(also need to bump in pyproject.toml)

2022-06-25 11:24 UTC, john-sandall commented on .pre-commit-config.yaml
>      hooks:
```
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
```

in pyproject.toml we now use 4.0.1 so I'm trying that here, not sure why autoupdate didn't upgrade that though

2022-06-25 11:24 UTC, john-sandall commented on .pre-commit-config.yaml
>      hooks:
autoupdate won't catch the inner versions, these must be manually checked, e.g. https://pypi.org/project/flake8-eradicate/ is now at 1.2.1

2022-06-25 11:46 UTC, merged